version: 'Smile-1.0.{build}'
language: cpp
branches:
  only:
  - master
sudo: required

compiler: gcc

#env: QT_BASE="512"
matrix:
  include:
#ubuntu 16.04 LTS(xenial)
    - os: linux
      dist: xenial
      env: 
        targetFile=Smile
        releaseName=Smile_ubuntu_xenial_x64.AppImage
        qtppa="ppa:beineri/opt-qt-5.12.3-xenial"
      cache:
        bundler: true
        apt: true
        directories:
            - /opt/qt*/


  #macOS 10.14 with xcode 11
    - os: osx
      osx_image: xcode11
      env: 
        targetFile=Smile
        releaseName=Smile_macos10-14_xcode10-2.dmg
        qtDir=/usr/local/opt/qt
      cache:
        bundler: true
        directories:
            - /usr/local/Cellar/qt/
            - /usr/local/opt/qt/
            
group: deprecated-2019Q1


before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo add-apt-repository ${qtppa} -y; sudo apt-get update -qq; sudo apt-get install -y libglew-dev libglfw3-dev; sudo apt-get install -y qt512-meta-minimal; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; brew install qt; brew link qt --force; fi 



before_script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then source /opt/qt512/bin/qt512-env.sh ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then export PATH=${qtDir}/bin:${PATH} ; fi

script:
  - cd Smile
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then qmake ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then make ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then qmake CONFIG+=release ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then make ; fi
  
before_deploy:
  - ls
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then macdeployqt ${targetFile}.app -qmldir=${qtDir}/qml -verbose=1 -dmg ; mv ${targetFile}.dmg ${releaseName} ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then wget https://github.com/linuxdeploy/linuxdeploy/releases/download/continuous/linuxdeploy-x86_64.AppImage ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then chmod a+x linuxdeploy-x86_64.AppImage ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then OUTPUT="$releaseName" ./linuxdeploy-x86_64.AppImage --appimage-extract-and-run -e Smile --appdir appdir -e Smile -i appimage/smile-icon.svg -d appimage/smile.desktop --output appimage ; fi
  - ls
  
deploy:
  provider: releases 
  api_key: $GITHUB_OAUTH_TOKEN 
  file: ${releaseName}
  skip_cleanup: true
  draft: false
  prerelease: true
  on:
    branch: master


notifications:
    email: false
