version: 'Smile-1.0.{build}'
branches:
  except:
    - project/travis

before_build:
  - set msvc=msvc2017
  - set QTDIR=C:\Qt\5.12\msvc2017_64
  - set PATH=%PATH%;%QTDIR%\bin;
  - call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"
build_script:
  - qmake Smile/Smile.pro
  - nmake release
  - cd release
  - windeployqt --release Smile.exe
  
  - qmake C:/projects/smile/Test/Test.pro
  - nmake release
  - cd release
  - copy "C:\projects\smile\Smile\Server\*.db" "C:/projects/smile/release"
  - copy "C:\projects\smile\Smile\Server\*.db" "C:/projects/smile/release/release"
  - windeployqt --release Test.exe
  - .\Test.exe -xunitxml > tests.xml 
  
on_finish:
  - ps: (new-object net.webclient).UploadFile("https://ci.appveyor.com/api/testresults/junit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\tests.xml))
artifacts:
  - path: release
    name: Smile_qt512_vs2017_x64

deploy:
  # Deploy to GitHub Releases
  - provider: GitHub
    
    description: '"Smile Test Release"'
    draft: false
    prerelease: true
    auth_token:
      secure: raX5hiieSXgtTiXFvRQafRFN2qA4rg9evnBREHR/pGn9o/B4wF7N6qA9Vs5HdiXI
    on:
      branch: master
