image: Visual Studio 2015

environment:
  Configuration: Release
  matrix:
  - Platform: MinGW32
    PlatformToolset: 5.3.0
  - Platform: MinGW64
    PlatformToolset: 5.3.0

install:
  - set QTDIR=C:\Qt\5.11.2\mingw53_32
  - set PATH=%PATH%;%QTDIR%\bin;C:\MinGW\bin

build_script:
  - qmake ALL_in_one.pro
  - mingw32-make

deploy:
  on:
    branch: master                 # ðåëèçû òîëüêî èç âåòêè master
    APPVEYOR_REPO_TAG: true        # òîëüêî åñëè èìååòñÿ ïðèêðåïëåííûé tag

  provider: GitHub                         # âûêëàäûâàåì íà GitHub Releases
  description: 'Bump version to $(APPVEYOR_REPO_TAG_NAME).$(APPVEYOR_BUILD_NUMBER)' # tag êàê èìÿ ðåëèçà
  
  artifact: /.*\.zip/ # ðåãóëÿðíîå âûðàæåíèå, îïèñûâàþùåå âñå àðòåôàêòû äàííîãî ðåëèçà
  force_update: true  # ïåðåçàïèñûâàòü àðòåôàêòû, åñëè ôàéë ñ òàêèì èìåíåì óæå èìååòñÿ
  draft: false
  prerelease: false
