version: 'Smile-1.0.{build}'
branches:
  only:
    - master
    
  environment:
  matrix:
  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    platform: x86
    qt: 5.12
    releaseName: Smile_qt512_vs2017_x86
  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    platform: x64
    qt: 5.12
    releaseName: Smile_qt512_vs2017_x64
before_build:
  - if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2017" set msvc=msvc2017
  - if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2017" set vs=C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build
  - if "%platform%"=="x86" set QTDIR=C:\Qt\%qt%\%msvc%
  - if "%platform%"=="x64" set QTDIR=C:\Qt\%qt%\%msvc%_64
  - set PATH=%PATH%;%QTDIR%\bin;
  - if "%platform%"=="x86" set vcvarsall=%vs%\vcvarsall.bat
  - if "%platform%"=="x64" set vcvarsall=%vs%\vcvarsall.bat
  - if "%platform%"=="x86" call "%vcvarsall%" x86
  - if "%platform%"=="x64" call "%vcvarsall%" x64
build_script:
  - qmake Smile/Smile.pro
  - nmake release
  - cd release
  - windeployqt --release Smile.exe
  
  - qmake C:/projects/smile/Test/Test.pro
  - nmake release
  - cd release
  - copy "C:\projects\smile\Smile\Server\*.db" "C:/projects/smile/release"
  - copy "C:\projects\smile\Smile\Server\*.db" "C:/projects/smile/release/release"
  - windeployqt --release Test.exe
  - .\Test.exe -xunitxml > tests.xml 
  
on_finish:
  - ps: (new-object net.webclient).UploadFile("https://ci.appveyor.com/api/testresults/junit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\tests.xml))
artifacts:
  - path: release
    name: $(releaseName)
deploy:
  # Deploy to GitHub Releases
  - provider: GitHub
    description: '"Smile Test Release"'
    draft: false
    prerelease: true
    auth_token:
      secure: raX5hiieSXgtTiXFvRQafRFN2qA4rg9evnBREHR/pGn9o/B4wF7N6qA9Vs5HdiXI
    on:
      branch: master
